---
- op: replace
  path: /spec/source/repoURL
  value: https://github.com/Katka92/infra-deployments.git
- op: replace
  path: /spec/source/targetRevision
  value: preview-remove_cluster_registration
