apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ../../base/external-secrets
- https://github.com/redhat-appstudio/integration-service/config/default?ref=2b89dd379969c6fbd5ee33a8cc7d4a85fb736237
- https://github.com/redhat-appstudio/integration-service/config/snapshotgc?ref=f7bb0788791c37b7a82a98555dc710d434e36a56

images:
- name: quay.io/redhat-appstudio/integration-service
  newName: quay.io/redhat-appstudio/integration-service
  newTag: 2b89dd379969c6fbd5ee33a8cc7d4a85fb736237

configMapGenerator:
- name: console-url
  literals:
    - CONSOLE_URL="https://console.redhat.com/preview/application-pipeline/ns/{{ .Namespace }}/pipelinerun/{{ .PipelineRunName }}"

namespace: integration-service

patches:
  - path: pipelines-as-code-secret.yaml
    target:
      name: pipelines-as-code-secret
      kind: ExternalSecret
      group: external-secrets.io
      version: v1beta1
  - path: manager_resources_patch.yaml
