apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/enterprise-contract/enterprise-contract-controller/config/crd?ref=056018955f357fefbd709f8ded323f56cb426827
  - ecp.yaml
  - role.yaml
  - rolebinding.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: ec-defaults
    namespace: enterprise-contract-service
    literals:
      - verify_ec_task_bundle=quay.io/enterprise-contract/ec-task-bundle:aef44ffb2a30cf424af54df0fe992317fbdab074@sha256:0eb02c875add9d8b9257fad4ac4081dfdad4a921da9ed4c41c146c47f768c91b
      - verify_ec_task_git_url=https://github.com/enterprise-contract/ec-cli.git
      - verify_ec_task_git_revision=aef44ffb2a30cf424af54df0fe992317fbdab074
      - verify_ec_task_git_pathInRepo=tasks/verify-enterprise-contract/0.1/verify-enterprise-contract.yaml
images:
  - name: quay.io/redhat-appstudio/enterprise-contract-controller
    newName: quay.io/redhat-appstudio/enterprise-contract-controller
    newTag: 056018955f357fefbd709f8ded323f56cb426827
